### ISSUE TITLE
Web audio resources in compile-to-JS languages (ClojureScript, etc)

### ISSUE THREAD

**Issue by esbullington** [notthetup/awesome-webaudio#18]
Should I create a new category for Web Audio resources in compile-to-JS languages, or simply create a normal listing with a mention of the language in the description?  For example, [Klangmeister](https://ctford.github.io/klangmeister/).

Thanks for putting this resource up.

**Comment by notthetup** [comment]
Yea. A new category makes more sense at least for now as I see people use such projects mostly by themselves.

**Comment by notthetup** [comment]
Also, thank you for contributing! :)
